/**
 * US State jurisdictions with real estate law variants
 * @module constants/jurisdictions
 */

/**
 * Jurisdiction/state information
 */
export interface Jurisdiction {
  /** State code (2-letter) */
  code: string;
  /** Full state name */
  name: string;
  /** Closing type (attorney/title/escrow) */
  closingType: ClosingType;
  /** Whether attorney is required at closing */
  attorneyRequired: boolean;
  /** Whether state uses deed of trust or mortgage */
  securityInstrument: 'DEED_OF_TRUST' | 'MORTGAGE' | 'BOTH';
  /** Foreclosure type */
  foreclosureType: 'JUDICIAL' | 'NON_JUDICIAL' | 'BOTH';
  /** Community property state */
  communityProperty: boolean;
  /** Homestead exemption available */
  homesteadExemption: boolean;
  /** Transfer tax rate (per $1000) */
  transferTaxRate: number;
  /** Recording fee (approximate base) */
  baseRecordingFee: number;
  /** Attorney review period (days, 0 if none) */
  attorneyReviewPeriod: number;
  /** Typical due diligence period (days) */
  typicalDueDiligenceDays: number;
  /** Wet funding state (funds required at closing) */
  wetFunding: boolean;
  /** Additional notes */
  notes?: string;
}

/**
 * Closing type categories
 */
export type ClosingType = 'ATTORNEY' | 'TITLE' | 'ESCROW';

/**
 * US State jurisdictions
 */
export const JURISDICTIONS: Record<string, Jurisdiction> = {
  AL: {
    code: 'AL',
    name: 'Alabama',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0.5,
    baseRecordingFee: 25,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  AK: {
    code: 'AK',
    name: 'Alaska',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 25,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: false,
  },
  AZ: {
    code: 'AZ',
    name: 'Arizona',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: true,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 30,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: false,
  },
  AR: {
    code: 'AR',
    name: 'Arkansas',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'BOTH',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 3.3,
    baseRecordingFee: 15,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  CA: {
    code: 'CA',
    name: 'California',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: true,
    homesteadExemption: true,
    transferTaxRate: 1.1,
    baseRecordingFee: 15,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 17,
    wetFunding: false,
    notes: 'Documentary transfer tax varies by county',
  },
  CO: {
    code: 'CO',
    name: 'Colorado',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'BOTH',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0.01,
    baseRecordingFee: 13,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  CT: {
    code: 'CT',
    name: 'Connecticut',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 7.5,
    baseRecordingFee: 60,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  DE: {
    code: 'DE',
    name: 'Delaware',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: false,
    transferTaxRate: 4.0,
    baseRecordingFee: 36,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  FL: {
    code: 'FL',
    name: 'Florida',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 7.0,
    baseRecordingFee: 10,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 15,
    wetFunding: true,
    notes: 'Documentary stamp tax and strong homestead protection',
  },
  GA: {
    code: 'GA',
    name: 'Georgia',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 1.0,
    baseRecordingFee: 50,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  HI: {
    code: 'HI',
    name: 'Hawaii',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'BOTH',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 1.0,
    baseRecordingFee: 50,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: false,
  },
  ID: {
    code: 'ID',
    name: 'Idaho',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: true,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 10,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: false,
  },
  IL: {
    code: 'IL',
    name: 'Illinois',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 1.0,
    baseRecordingFee: 50,
    attorneyReviewPeriod: 5,
    typicalDueDiligenceDays: 5,
    wetFunding: true,
    notes: 'Five business day attorney review period',
  },
  IN: {
    code: 'IN',
    name: 'Indiana',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 20,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  IA: {
    code: 'IA',
    name: 'Iowa',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'BOTH',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 1.6,
    baseRecordingFee: 10,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  KS: {
    code: 'KS',
    name: 'Kansas',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 26,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  KY: {
    code: 'KY',
    name: 'Kentucky',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 1.0,
    baseRecordingFee: 15,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  LA: {
    code: 'LA',
    name: 'Louisiana',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: true,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 75,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'Uses Napoleonic civil law system',
  },
  ME: {
    code: 'ME',
    name: 'Maine',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 4.4,
    baseRecordingFee: 26,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  MD: {
    code: 'MD',
    name: 'Maryland',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: false,
    transferTaxRate: 5.0,
    baseRecordingFee: 60,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'Transfer and recordation tax varies by county',
  },
  MA: {
    code: 'MA',
    name: 'Massachusetts',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 4.56,
    baseRecordingFee: 75,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  MI: {
    code: 'MI',
    name: 'Michigan',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 7.5,
    baseRecordingFee: 30,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  MN: {
    code: 'MN',
    name: 'Minnesota',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'BOTH',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 3.3,
    baseRecordingFee: 46,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  MS: {
    code: 'MS',
    name: 'Mississippi',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 25,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  MO: {
    code: 'MO',
    name: 'Missouri',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 24,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  MT: {
    code: 'MT',
    name: 'Montana',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 10,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: false,
  },
  NE: {
    code: 'NE',
    name: 'Nebraska',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 2.25,
    baseRecordingFee: 10,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  NV: {
    code: 'NV',
    name: 'Nevada',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: true,
    homesteadExemption: true,
    transferTaxRate: 2.55,
    baseRecordingFee: 35,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: false,
  },
  NH: {
    code: 'NH',
    name: 'New Hampshire',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 15.0,
    baseRecordingFee: 25,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'High transfer tax ($7.50/$1000 each buyer and seller)',
  },
  NJ: {
    code: 'NJ',
    name: 'New Jersey',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: false,
    transferTaxRate: 6.0,
    baseRecordingFee: 65,
    attorneyReviewPeriod: 3,
    typicalDueDiligenceDays: 3,
    wetFunding: true,
    notes: 'Three day attorney review period',
  },
  NM: {
    code: 'NM',
    name: 'New Mexico',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: true,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 25,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: false,
  },
  NY: {
    code: 'NY',
    name: 'New York',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 4.0,
    baseRecordingFee: 125,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'NYC has additional transfer taxes; mansion tax applies over $1M',
  },
  NC: {
    code: 'NC',
    name: 'North Carolina',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 2.0,
    baseRecordingFee: 26,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 14,
    wetFunding: true,
    notes: 'Due diligence period typically 14-21 days',
  },
  ND: {
    code: 'ND',
    name: 'North Dakota',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 10,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  OH: {
    code: 'OH',
    name: 'Ohio',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 4.0,
    baseRecordingFee: 30,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  OK: {
    code: 'OK',
    name: 'Oklahoma',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'BOTH',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0.75,
    baseRecordingFee: 18,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  OR: {
    code: 'OR',
    name: 'Oregon',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'BOTH',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 65,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: false,
    notes: 'Some counties have local transfer taxes',
  },
  PA: {
    code: 'PA',
    name: 'Pennsylvania',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: false,
    transferTaxRate: 10.0,
    baseRecordingFee: 175,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'Combined state and local transfer tax typically 2% total',
  },
  RI: {
    code: 'RI',
    name: 'Rhode Island',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: false,
    transferTaxRate: 4.6,
    baseRecordingFee: 50,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  SC: {
    code: 'SC',
    name: 'South Carolina',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 3.7,
    baseRecordingFee: 25,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  SD: {
    code: 'SD',
    name: 'South Dakota',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 1.0,
    baseRecordingFee: 30,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  TN: {
    code: 'TN',
    name: 'Tennessee',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 3.7,
    baseRecordingFee: 20,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  TX: {
    code: 'TX',
    name: 'Texas',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: true,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 20,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'Strong homestead protections; option period common',
  },
  UT: {
    code: 'UT',
    name: 'Utah',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 40,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 14,
    wetFunding: false,
  },
  VT: {
    code: 'VT',
    name: 'Vermont',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 12.5,
    baseRecordingFee: 15,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'Property transfer tax with exemptions for principal residence',
  },
  VA: {
    code: 'VA',
    name: 'Virginia',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 2.5,
    baseRecordingFee: 35,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'Grantor/grantee tax; additional regional taxes in Northern VA',
  },
  WA: {
    code: 'WA',
    name: 'Washington',
    closingType: 'ESCROW',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: true,
    homesteadExemption: true,
    transferTaxRate: 15.4,
    baseRecordingFee: 85,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: false,
    notes: 'Real Estate Excise Tax (REET) tiered by sale price',
  },
  WV: {
    code: 'WV',
    name: 'West Virginia',
    closingType: 'ATTORNEY',
    attorneyRequired: true,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 4.4,
    baseRecordingFee: 25,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  WI: {
    code: 'WI',
    name: 'Wisconsin',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'JUDICIAL',
    communityProperty: true,
    homesteadExemption: true,
    transferTaxRate: 3.0,
    baseRecordingFee: 30,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'Marital property state (similar to community property)',
  },
  WY: {
    code: 'WY',
    name: 'Wyoming',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'MORTGAGE',
    foreclosureType: 'BOTH',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 0,
    baseRecordingFee: 12,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
  },
  DC: {
    code: 'DC',
    name: 'District of Columbia',
    closingType: 'TITLE',
    attorneyRequired: false,
    securityInstrument: 'DEED_OF_TRUST',
    foreclosureType: 'NON_JUDICIAL',
    communityProperty: false,
    homesteadExemption: true,
    transferTaxRate: 11.0,
    baseRecordingFee: 35,
    attorneyReviewPeriod: 0,
    typicalDueDiligenceDays: 10,
    wetFunding: true,
    notes: 'Recordation and transfer tax; reduced rate for first-time homebuyers',
  },
} as const;

/**
 * Get all state codes
 */
export const STATE_CODES = Object.keys(JURISDICTIONS) as readonly string[];

/**
 * Get all community property states
 */
export const COMMUNITY_PROPERTY_STATES = Object.entries(JURISDICTIONS)
  .filter(([_, j]) => j.communityProperty)
  .map(([code]) => code) as readonly string[];

/**
 * Get all attorney-required states
 */
export const ATTORNEY_REQUIRED_STATES = Object.entries(JURISDICTIONS)
  .filter(([_, j]) => j.attorneyRequired)
  .map(([code]) => code) as readonly string[];

/**
 * Get states by closing type
 */
export const getStatesByClosingType = (type: ClosingType): readonly string[] =>
  Object.entries(JURISDICTIONS)
    .filter(([_, j]) => j.closingType === type)
    .map(([code]) => code);

/**
 * Get jurisdiction by code
 */
export const getJurisdiction = (code: string): Jurisdiction | undefined =>
  JURISDICTIONS[code.toUpperCase()];
