name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you're requesting.
      placeholder: One-line summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a frustration?
      placeholder: |
        I'm always frustrated when...
        Currently, there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        I would like to be able to...
        The feature should work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: |
        I've considered using...
        Another approach might be...

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the application would this feature affect?
      multiple: true
      options:
        - API / Backend
        - Web / Frontend
        - Database
        - Authentication
        - Document Processing
        - Search / Discovery
        - Reporting / Analytics
        - Integration / API
        - UI / UX
        - Performance
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking work)
        - High (Significantly impacts productivity)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Who would benefit from this feature?
      multiple: true
      options:
        - End Users (Paralegals/Attorneys)
        - Administrators
        - Developers
        - All Users

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe the feature from a user's perspective.
      placeholder: |
        As a [type of user], I want to [action] so that [benefit].

        Example:
        As a paralegal, I want to bulk upload documents so that I can process multiple files at once.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Designs
      description: If you have any mockups, wireframes, or design ideas, please share them.
      placeholder: Drag and drop images here or provide links...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following.
      options:
        - label: I have searched existing issues/features to ensure this is not a duplicate
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: I am willing to help implement this feature (optional)
          required: false
